# Mellanox Bluefield build scripts

MLNX_BLUEFIELD_BUILD_SCRIPTS_VERSION = 3.6

MLNX_BLUEFIELD_BUILD_SCRIPTS = mlxbf-scripts_$(MLNX_BLUEFIELD_BUILD_SCRIPTS_VERSION)_$(CONFIGURED_ARCH).deb
$(MLNX_BLUEFIELD_BUILD_SCRIPTS)_SRC_PATH = $(PLATFORM_PATH)/bfscripts
SONIC_DPKG_DEBS += $(MLNX_BLUEFIELD_BUILD_SCRIPTS)
