# mellanox bluefield2 gpio driver

MLXBF2_GPIO_DRIVER_VERSION = 1.0
export MLXBF2_GPIO_DRIVER_VERSION

MLXBF2_GPIO_DRIVER = gpio-mlxbf2.ko
export MLXBF2_GPIO_DRIVER
$(MLXBF2_GPIO_DRIVER)_SRC_PATH = $(PLATFORM_PATH)/gpio-mlxbf2
$(MLXBF2_GPIO_DRIVER)_DEPENDS += $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON)
SONIC_MAKE_FILES += $(MLXBF2_GPIO_DRIVER)
