# mellanox gige driver

MLXBF_GIGE_DRIVER_VERSION = 1.1
export MLXBF_GIGE_DRIVER_VERSION

MLXBF_GIGE_DRIVER = mlxbf-gige.ko
export MLXBF_GIGE_DRIVER
$(MLXBF_GIGE_DRIVER)_SRC_PATH = $(PLATFORM_PATH)/mlxbf-gige
$(MLXBF_GIGE_DRIVER)_DEPENDS += $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON)
SONIC_MAKE_FILES += $(MLXBF_GIGE_DRIVER)
