# sonic bluefield one image installer

SONIC_ONE_IMAGE = sonic-bluefield-arm64.bin
$(SONIC_ONE_IMAGE)_MACHINE = bluefield-arm64
$(SONIC_ONE_IMAGE)_IMAGE_TYPE = onie

$(SONIC_ONE_IMAGE)_INSTALLS += $(SYSTEMD_SONIC_GENERATOR)
$(SONIC_ONE_IMAGE)_INSTALLS += $(MNLX_BLUEFIELD_BUILD_SCRIPTS)
$(SONIC_ONE_IMAGE)_FILES += $(TMFIFO_DRIVER)
$(SONIC_ONE_IMAGE)_FILES += $(MLXBF2_GPIO_DRIVER)
$(SONIC_ONE_IMAGE)_FILES += $(MLXBF_GIGE_DRIVER)

ifeq ($(INSTALL_DEBUG_TOOLS),y)
$(SONIC_ONE_IMAGE)_DOCKERS += $(SONIC_INSTALL_DOCKER_DBG_IMAGES)
$(SONIC_ONE_IMAGE)_DOCKERS += $(filter-out $(patsubst %-$(DBG_IMAGE_MARK).gz,%.gz, $(SONIC_INSTALL_DOCKER_DBG_IMAGES)), $(SONIC_INSTALL_DOCKER_IMAGES))
else
$(SONIC_ONE_IMAGE)_DOCKERS = $(SONIC_INSTALL_DOCKER_IMAGES)
endif
SONIC_INSTALLERS += $(SONIC_ONE_IMAGE)
