# tmfifo driver

TMFIFO_DRIVER_VERSION = 1.5
export TMFIFO_DRIVER_VERSION

TMFIFO_DRIVER = mlxbf-tmfifo.ko
export TMFIFO_DRIVER
$(TMFIFO_DRIVER)_SRC_PATH = $(PLATFORM_PATH)/tmfifo
$(TMFIFO_DRIVER)_DEPENDS += $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON)
SONIC_MAKE_FILES += $(TMFIFO_DRIVER)
